name: Publish gh-pages

on:
  push:
    branches: [ utabe-patch-1 ]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository 
    - uses: actions/checkout@v2
      
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: 3.8
        activate-environment: sphinx-doc
        environment-file: environment.yml    
    
    - name: Build docs
      shell: bash -l {0}
      run: |
        make clean
        make html
        cp -r build/html/* docs/

#     # Publish built docs to gh-pages branch.
#     # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/openteamsinc/semantic-http-spec.git --branch docs --single-branch docs
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
#         # The above command will fail if no changes were present, so we ignore
#         # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: docs
        directory: docs
        github_token: ${{ secrets.SEMANTIC_HTTP_SPEC_KEY }}
